name: Pull Request
on: 
  pull_request:
    types: ['opened', 'reopened', 'edited', 'synchronize']
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  validate_pr:
    name: 'Validate PR'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run PR Validator
        uses: ./validate-pr
