name: Pull Request
on: pull_request
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  validate_pr:
    name: 'Validate PR'
    runs-on: ubuntu-latest
    steps:
      - name: Run PR Validator
        uses: ./validate-pr
